# -*- coding: utf-8 -*-
"""BeritaCheck_DataPreprocessing_NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1th1nyXbpM_7ALE29SN-BoNGjQTv5Y_v0
"""

# RAW DATA HARVESTING PIPELINE
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def scrape_malaysian_news(url, outlet, index, total):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    }
    print(f"🔄 [{index}/{total}] Scraping {outlet}...")
    try:
        if pd.isna(url) or str(url).strip() == "" or "http" not in str(url):
            return "No URL provided"

        response = requests.get(url, headers=headers, timeout=10)
        if response.status_code != 200:
            return f"Error: HTTP {response.status_code}"

        soup = BeautifulSoup(response.text, 'html.parser')
        paragraphs = soup.find_all('p')

        clean_paragraphs = [p.text.strip() for p in paragraphs if len(p.text.strip()) > 20]
        full_text = " ".join(clean_paragraphs)

        if len(full_text) > 0:
            print(f"✅ Success! Captured {len(clean_paragraphs)} paragraphs.")
        else:
            print(f"⚠️ Warning: No valid paragraph text found.")
        return full_text
    except Exception as e:
        return f"Scraping failed: {str(e)}"

# Execute Harvest
df = pd.read_csv(r'C:\Users\nutte\Downloads\WID3002_NLP\BeritaCheck\news_links.csv')
scraped_bodies = []
for idx, row in df.iterrows():
    text_content = scrape_malaysian_news(row['url'], row['news_outlet'], idx + 1, len(df))
    scraped_bodies.append(text_content)
    time.sleep(2)

df['Raw_Text'] = scraped_bodies
df.to_csv('scraped_raw_output.csv', index=False)
print("\n🎉 ALL DONE! Raw dataset saved to 'scraped_raw_output.csv'")

# TEXT POLISHING & DATA ANOMALY FILTER
import pandas as pd
import re

# Load Data & Drop Broken Media Outlets
df = pd.read_csv('scraped_raw_output.csv')
bad_outlets = ['NST', 'The Sun Malaysia', 'The Malaysian Reserve']
df = df[~df['news_outlet'].isin(bad_outlets)]

# Advanced Malaysian Text Polishing Function
def polish_malaysian_text(text):
    text = str(text)

    # Clean out subscription, newsletter and ad banner noise
    ad_phrases = [
        r"Subscribe to our FREE\s?Newsletter",
        r"Telegram and WhatsApp channels",
        r"Click on the points to redeem your rewards",
        r"Stay signed in to save the points"
    ]
    for phrase in ad_phrases:
        text = re.sub(phrase, "", text, flags=re.IGNORECASE)

    # Strip Malaysian media datelines (KUALA LUMPUR, Bernama, The Edge styles)
    text = re.sub(r"^[A-Z\s]+,\s[A-Z][a-z]+\s\d+\s\([^)]+\)\s?[-–—]+", "", text)
    text = re.sub(r"^[A-Z\s]+\s\([^)]+\):\s?", "", text)
    text = re.sub(r"^[A-Z\s]+,\s[A-Z][a-z]+\s\d+\s?[-–—]+", "", text)

    return " ".join(text.split())

df['Raw_Text'] = df['Raw_Text'].apply(polish_malaysian_text)

# Size and Duplicate Filters
df['Word_Count'] = df['Raw_Text'].apply(lambda x: len(str(x).split()))
df = df[df['Word_Count'] > 150]
df = df.drop_duplicates(subset=['Raw_Text'])

# Run Dataset Diagnostics
print("="*60)
print("FINAL NLP DATASET DIAGNOSTIC")
print("="*60)
print(f"Total High-Fidelity Articles Remaining: {len(df)}")
print("\nArticle Count per Surviving News Outlet:")
print(df['news_outlet'].value_counts())
print("="*60)

# Save intermediate clean file
df.to_csv('scraped_raw_output.csv', index=False)

# MASTER BIAS PROCESSING ENGINE
import re
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
from textblob import TextBlob
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_distances
from sklearn.preprocessing import LabelEncoder

nltk.download('stopwords', quiet=True)
stop_words = set(stopwords.words('english'))

df = pd.read_csv('scraped_raw_output.csv')
print(f"Processing Phase 2 Engine. Inputs: {len(df)} rows.")

# DUPLICATE AND LINGUISTIC CLEANSING
df = df.drop_duplicates(subset=['news_outlet', 'Raw_Text'])

def deep_clean_text(text):
    text = str(text).lower()
    text = re.sub(r'http\S+|www\.\S+', '', text)
    text = re.sub(r'[^a-z0-9\s]', '', text)
    return " ".join(text.split())

df['Clean_Text'] = df['Raw_Text'].apply(deep_clean_text)
df['Processed_Text'] = df['Clean_Text'].apply(lambda x: " ".join([w for w in x.split() if w not in stop_words]))

# MATH BIAS FEATURE ENGINEERING
df['Subjectivity_Score'] = df['Raw_Text'].apply(lambda x: TextBlob(str(x)).sentiment.subjectivity)
df['Framing_Distance_Score'] = 0.0

for topic in df['topic_id'].unique():
    mask = df['topic_id'] == topic
    topic_text = df[mask]['Processed_Text'].tolist()
    if len(topic_text) > 1:
        vectorizer = TfidfVectorizer()
        tfidf_matrix = vectorizer.fit_transform(topic_text).toarray()
        consensus_vector = np.mean(tfidf_matrix, axis=0).reshape(1, -1)
        df.loc[mask, 'Framing_Distance_Score'] = cosine_distances(tfidf_matrix, consensus_vector).flatten()

# POLITICAL DENSITY BIAS ENCODING
political_keywords = [
    'minister', 'government', 'anwar', 'ibrahim', 'dzulkefly', 'bersatu', 'loke siew fook',
    'macc', 'corruption', 'subsidies', 'najib', 'razak', 'court', 'amend', 'state speaker',
    'assemblyman', 'parti', 'dap', 'pkr', 'pas', 'perikatan', 'nasional', 'barisan', 'umno'
]

df['Political_Density_Score'] = df['Processed_Text'].apply(
    lambda x: sum(1 for w in str(x).split() if any(kw in w for kw in political_keywords)) / max(1, len(str(x).split()))
)

df['Bias_Label'] = df['Political_Density_Score'].apply(lambda score: "Political-Framed" if score > 0.035 else "Non-Political/Objective")
df['Bias_Encoded'] = LabelEncoder().fit_transform(df['Bias_Label'])

# INSTITUTIONAL OUTLET PROFILE MAPPING
baseline_profile_map = {
    "Bernama": "State-Institutional", "Malay Mail": "Mainstream-Commercial", "The Star": "Mainstream-Commercial",
    "The Edge Malaysia": "Analytical-Financial", "Free Malaysia Today": "Independent-Alternative",
    "The Rakyat Post": "Independent-Alternative", "The Strait Times": "Regional-External"
}
df['Outlet_Profile'] = df['news_outlet'].map(baseline_profile_map)
df['Outlet_Profile_Encoded'] = LabelEncoder().fit_transform(df['Outlet_Profile'])

# Final Filter and Export
df['Final_Word_Count'] = df['Processed_Text'].apply(lambda x: len(str(x).split()))
df = df[df['Final_Word_Count'] > 120]
df.to_csv('final_preprocessed_news.csv', index=False)

print("="*70)
print(f"PIPELINE REFACTORED SUCCESSFULLY!")
print(f"Final Model Entries Exported: {len(df)}")
print(df['Bias_Label'].value_counts())
print("="*70)

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load our preprocessed clean news text data
df = pd.read_csv('final_preprocessed_news.csv')
print(f"Encoding bias dimensions for {len(df)} model-ready articles...")
print("="*70)

# 1. Define a robust Malaysian Political Lexicon to assess semantic density
political_keywords = [
    'minister', 'government', 'anwar', 'ibrahim', 'dzulkefly', 'bersatu', 'loke siew fook',
    'macc', 'corruption', 'subsidies', 'najib', 'razak', 'court', 'amend', 'state speaker',
    'assemblyman', 'parti', 'dap', 'pkr', 'pas', 'perikatan', 'nasional', 'barisan', 'umno',
    'jurisdiction', 'legal', 'execution', 'allocation', 'procurement', 'policy', 'ft'
]

def calculate_political_density(text):
    text_lower = str(text).lower()
    words = text_lower.split()
    if not words:
        return 0.0
    # Count how many political anchors appear in the text
    match_count = sum(1 for word in words if any(kw in word for kw in political_keywords))
    return match_count / len(words)

# Compute raw density values
df['Political_Density_Score'] = df['Processed_Text'].apply(calculate_political_density)

# 2. Assign the structural Target Label
# If an article has heavy political keyword weights AND drifts significantly from the neutral average
# or exhibits heightened subjectivity, it is tagged as a Politically Framed Narrative.
density_threshold = 0.035  # ~3.5% of the text consists of political/policy vocabulary

def assign_bias_category(row):
    if row['Political_Density_Score'] > density_threshold:
        return "Political-Framed"
    else:
        return "Non-Political/Objective"

df['Bias_Label'] = df.apply(assign_bias_category, axis=1)

# 3. Label Encode the Categorical Boundaries into Numeric Flags (0 and 1)
le = LabelEncoder()
df['Bias_Encoded'] = le.fit_transform(df['Bias_Label'])

print("Bias encoding layer processed successfully.")
print("\nFinal Target Label Distribution:")
print(df['Bias_Label'].value_counts())
print("-"*70)

# Display a quick verification matrix slice to review the work
print(df[['news_outlet', 'topic_id', 'Political_Density_Score', 'Bias_Label', 'Bias_Encoded']].head(10))
print("="*70)

# Save the absolute model-ready final frame
df.to_csv('final_preprocessed_news.csv', index=False)
print("ALL DONE! Your finalized file 'final_preprocessed_news.csv' is complete.")

import pandas as pd
import spacy
from nltk.stem import PorterStemmer
from textblob import TextBlob
from sklearn.preprocessing import LabelEncoder

print("Loading the digital dictionaries and tools...")
nlp = spacy.load("en_core_web_sm")
stemmer = PorterStemmer()

# load file
df = pd.read_csv('final_preprocessed_news.csv')
print(f"Loaded {len(df)} articles. Processing text (this might take a minute)...")

# Lemmatization
def get_lemmas(text):
    return " ".join([word.lemma_.lower() for word in nlp(str(text)) if not word.is_punct and not word.is_space and not word.is_stop])

# Stemming
def get_stems(text):
    return " ".join([stemmer.stem(word.text.lower()) for word in nlp(str(text)) if not word.is_punct and not word.is_space and not word.is_stop])

print("Doing Lemmatization...")
df['Lemmatized_Text'] = df['Raw_Text'].apply(get_lemmas)
print("Doing Stemming...")
df['Stemmed_Text'] = df['Raw_Text'].apply(get_stems)

# Sentiment Labeler
print("Scanning for Emotion (Sentiment Analysis)...")
def get_sentiment(text):
    # use 'Raw_Text' here because TextBlob needs full sentences and grammar to read emotion
    score = TextBlob(str(text)).sentiment.polarity
    if score > 0.1: return "Positive"
    elif score < -0.1: return "Negative"
    else: return "Neutral"

# create the text label (Positive/Negative/Neutral)
df['Sentiment_Label'] = df['Raw_Text'].apply(get_sentiment)

# Create the number label (0, 1, 2)
le = LabelEncoder()
df['Sentiment_Encoded'] = le.fit_transform(df['Sentiment_Label'])

# final export
print("\nSaving the master data...")
df.to_csv('READY_FOR_MODELS.csv', index=False)

print("="*60)
print("ALL DONE! Your master dataset is ready")
print(f"Total columns saved: {len(df.columns)}")
print("File saved as 'READY_FOR_MODELS.csv'")
print("="*60)

# print
df[['news_outlet', 'Bias_Label', 'Sentiment_Label', 'Sentiment_Encoded']].head(5)


import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import Dataset, DataLoader
from transformers import(
    BertTokenizer,
    BertForSequenceClassification,
    RobertaTokenizer,
    RobertaForSequenceClassification,
    get_linear_schedule_with_warmup
)
from torch.optim import AdamW

#check GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")
if torch.cuda.is_available():
    print(f"GPU name: {torch.cuda.get_device_name(0)}")

import pandas as pd
import os # Added for file path checking

#Load final preprocessed dataset from PART 1
file_path = 'READY_FOR_MODELS.csv'

# Check if the file exists before attempting to read it
if not os.path.exists(file_path):
    raise FileNotFoundError(f"Error: The file '{file_path}' was not found. Please ensure the preceding cells that generate this file have been executed successfully in the current session.")

df = pd.read_csv(file_path)

print(f'Total articles loaded: {len(df)}')
print(f'Columns: {len(df.columns)}')
print('='*60)
print('Bias Label Distribution: ')
print(df['Bias_Label'].value_counts())
print('\nSentiment Label Distribution: ')
print(df['Sentiment_Label'].value_counts())

#drop rows with missing text
df = df.dropna(subset=['Raw_Text']) # Corrected 'Raw Text' to 'Raw_Text'
df['Raw_Text'] = df['Raw_Text'].astype(str) # Corrected 'Raw Text' to 'Raw_Text'
print(f'\nRows after cleaning nulls: {len(df)}')

#custom pytorch dataset class

class NewsDataset(Dataset):
  """
  PyTorch Dataset wrapper for tokenized news articles.
  Works for both binary (bias) and multi-class(sentiment) tasks.
  """
  def __init__(self, texts, labels, tokenizer, max_length=256):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

  def __len__(self):
    return len(self.texts)

  def __getitem__(self, idx):
    encoding = self.tokenizer(
        self.texts[idx],
        truncation=True,
        padding='max_length',
        max_length=self.max_length,
        return_tensors='pt'
    )
    return{
        'input_ids': encoding['input_ids'].squeeze(0),
        'attention_mask': encoding['attention_mask'].squeeze(0),
        'labels': torch.tensor(self.labels[idx], dtype=torch.long)
    }
print('NewDataset class defined.')

#Training and evaluation helper functions

def train_epoch(model, loader, optimizer, scheduler):
  """Run one full training epoch."""
  model.train()
  total_loss = 0
  for batch in loader:
    optimizer.zero_grad()
    input_ids = batch['input_ids'].to(device)
    attention_mask = batch['attention_mask'].to(device)
    labels = batch['labels'].to(device)

    outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
    loss = outputs.loss
    total_loss += loss.item()

    loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
    optimizer.step()
    scheduler.step()

  return total_loss / len(loader)

def evaluate(model, data_loader, label_names):
    model.eval()
    all_preds = []
    all_labels = []
    
    with torch.no_grad():
        for batch in data_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)
            
            outputs = model(input_ids, attention_mask=attention_mask)
            preds = torch.argmax(outputs.logits, dim=1)
            
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
            
    # Find unique classes actually present in the true labels or predictions
    unique_classes = np.unique(np.concatenate([all_labels, all_preds]))
    
    # Safely filter the target names array to match only the present active classes
    filtered_label_names = [label_names[i] for i in unique_classes if i < len(label_names)]
    
    # Print report matching exactly the dimensions present
    print(classification_report(all_labels, all_preds, labels=unique_classes, target_names=filtered_label_names))
    return all_preds, all_labels

def build_loaders(texts_train, texts_test, y_train, y_test, tokenizer, batch_size=16, max_length=256):
  """Tokenize splits and return DataLoaders."""
  train_dataset = NewsDataset(texts_train.tolist(), y_train.tolist(), tokenizer, max_length)
  test_dataset = NewsDataset(texts_test.tolist(), y_test.tolist(), tokenizer, max_length)

  train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
  test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
  return train_loader, test_loader

def fine_tune_bert(task_name, texts, labels, num_labels, label_names, epochs=3, batch_size=16, max_length=256, lr=2e-5):
  """
  Full BERT fine-tuning pipeline for a single classification task.
  Returns the trained model and tokenizer.
  """
  print(f'\n{"="*70}')
  print(f'Fine-Tuning BERT for {task_name.upper()}...')
  print(f'{"="*70}')

  # 1. Load tokenizer and model
  tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
  model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=num_labels).to(device)

  # 2. Train/test split
  x_train, x_test, y_train, y_test = train_test_split(texts, labels, test_size=0.2, random_state=42, stratify=labels)
  print(f'Train: {len(x_train)}| Test: {len(x_test)}')

  # 3. Build DataLoaders
  train_loader, test_loader = build_loaders(x_train, x_test, y_train, y_test, tokenizer, batch_size, max_length)

  # 4. Set up optimizer and scheduler
  optimizer = AdamW(model.parameters(), lr=lr, weight_decay=0.01)
  total_steps = len(train_loader) * epochs
  scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=int(0.1 * total_steps), num_training_steps=total_steps)

  # 5. Training loop
  for epoch in range(1, epochs + 1):
    avg_loss = train_epoch(model, train_loader, optimizer, scheduler)
    print(f'Epoch {epoch}/{epochs} | Average Loss: {avg_loss:.4f}')

  # 6. Final evaluation
  print(f'\n-- {task_name} Test Set Results ---')
  preds, true = evaluate(model, test_loader, label_names)
  return model, tokenizer, x_test, y_test, preds

print('Helper functions defined.')

"""## MODEL 1: BERT for Bias Detection

Task: **Binary Classification**

*   0 -> Non-Political/Objective
*   1 -> Political-Framed

"""

import pandas as pd
import os

# Load final preprocessed dataset from PART 1
file_path = 'READY_FOR_MODELS.csv'

# Check if the file exists before attempting to read it
if not os.path.exists(file_path):
    raise FileNotFoundError(f"Error: The file '{file_path}' was not found. Please ensure the preceding cells that generate this file have been executed successfully in the current session.")

df = pd.read_csv(file_path)

# drop rows with missing text
df = df.dropna(subset=['Raw_Text'])
df['Raw_Text'] = df['Raw_Text'].astype(str)

# Prepare bias inputs
# We use Raw_Text (full sentences) because BERT needs natural language, not stopword-stripped text

bias_texts = df['Raw_Text']
bias_labels = df['Bias_Encoded'] # 0= Non-Political, 1 = Political
bias_label_names = ['Non-Political/Objective', 'Political-Framed']

print('Bias Label Distribution: ')
print(pd.Series(bias_labels).value_counts())

#Fine-tune
bias_model, bias_tokenizer, bias_x_test, bias_y_test, bias_preds = fine_tune_bert(
    task_name='Bias Detection',
    texts=bias_texts,
    labels=bias_labels,
    num_labels=2,
    label_names=bias_label_names,
    epochs =3,
    batch_size=16,
    max_length=256,
    lr=2e-5
)

bias_model.save_pretrained('./models/beritacheck_bias_model')
bias_tokenizer.save_pretrained('./models/beritacheck_bias_model')
print('Bias detection model saved to ./beritacheck_bias_model')

"""## Model 2: RoBERTa for Sentiment Analysis"""

def fine_tune_roberta(task_name, texts, labels, num_labels, label_names, epochs=3, batch_size=16, max_length=256, lr=2e-5):
    print(f'\n{"="*70}')
    print(f'Fine-Tuning RoBERTa for {task_name.upper()}...')
    print(f'{"="*70}')

    tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
    model = RobertaForSequenceClassification.from_pretrained('roberta-base', num_labels=num_labels).to(device)

    # Train-test splitting configurations
    x_train, x_test, y_train, y_test = train_test_split(texts, labels, test_size=0.2, random_state=42, stratify=labels)
    train_loader, test_loader = build_loaders(x_train, x_test, y_train, y_test, tokenizer, batch_size, max_length)

    optimizer = AdamW(model.parameters(), lr=lr, weight_decay=0.01)
    total_steps = len(train_loader) * epochs
    scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=int(0.1 * total_steps), num_training_steps=total_steps)

    for epoch in range(1, epochs + 1):
        avg_loss = train_epoch(model, train_loader, optimizer, scheduler)
        print(f'Epoch {epoch}/{epochs} | Average Loss: {avg_loss:.4f}')

    print(f'\n-- {task_name} Test Set Results ---')
    # This now utilizes our updated dynamic evaluate method safely
    preds, true = evaluate(model, test_loader, label_names)
    return model, tokenizer, x_test, y_test, preds

sentiment_texts = df['Raw_Text'].astype(str)
sentiment_labels = df['Sentiment_Encoded'].astype(int)
sentiment_label_names = ['Negative', 'Neutral', 'Positive']

print('Sentiment Label Distribution:')
print(pd.Series(sentiment_labels).value_counts())

roberta_sentiment_model, roberta_sentiment_tokenizer, sent_x_test, sent_y_test, sent_preds = fine_tune_roberta(
    task_name='Sentiment Analysis',
    texts=sentiment_texts,
    labels=sentiment_labels,
    num_labels=3,
    label_names=sentiment_label_names,
    epochs=3,
    batch_size=16,
    max_length=256,
    lr=2e-5
)

roberta_sentiment_model.save_pretrained('./models/beritacheck_roberta_sentiment_model')
roberta_sentiment_tokenizer.save_pretrained('./models/beritacheck_roberta_sentiment_model')
print('RoBERTa sentiment model saved!')

print('\n-- RoBERTa Sentiment Final Evaluation --')
print(f'Accuracy: {accuracy_score(sent_y_test, sent_preds):.4f}')

# Dynamically identify which unique classes exist in your actual test splits
final_classes = np.unique(np.concatenate([sent_y_test, sent_preds]))
final_label_names = [sentiment_label_names[i] for i in final_classes if i < len(sentiment_label_names)]

# Print the report using the filtered active dimensions
print(classification_report(sent_y_test, sent_preds, labels=final_classes, target_names=final_label_names))